name: Deploy with Environment

on:
  workflow_dispatch:
    inputs:
      environmentName:
        description: 'Select the environment to get the manifest version.'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Show Environment Input"
        run: echo "EnvironmentName: ${{ github.event.inputs.environmentName }}"
