name: 'Deploy DoCoffee App in Staging'

on:
  milestone:
    types: [closed]

  workflow_dispatch: # Allow you to run this workflow manually from the Action tab
  
env:
  BUILD_CONFIGURATION: Staging
  BUILD_PLATFORM: AnyCPU
  CSPROJ_PATH: src\DoCoffee.App\DoCoffee.App.csproj  
  OUTPUT_DIRECTORY: ${{ github.workspace }}\src\DoCoffee.App\bin\Staging\app.publish
  BUILD_DIRECTORY: ${{ github.workspace }}\build
      
jobs:

  build-and-publish:
    runs-on: windows-latest 
    
    steps:

    - name: "Checkout Code"
      uses: actions/checkout@v4

    - name: "Update AppSettings"
      run: |              
            & "${{ env.BUILD_DIRECTORY }}\UpdateAppSettings.ps1" -FilePath "${{ github.workspace }}\src\DoCoffee.App\App.config" -Key "MySecret" -Value ${{ secrets.MY_SECRET }}
            & "${{ env.BUILD_DIRECTORY }}\UpdateAppSettings.ps1" -FilePath "${{ github.workspace }}\src\DoCoffee.App\App.config" -Key "ApiKey" -Value ${{ secrets.API_KEY }}
                    
    - name: 'Setup MSBuild'
      uses: microsoft/setup-msbuild@v2

    - name: 'Setup Nuget'
      uses: nuget/setup-nuget@v2

    - name: 'Nuget Restore Packages'
      run: nuget restore ${{ env.CSPROJ_PATH }} -PackagesDirectory "src/packages"
      
    - name: "Increment Revision"     
      run: |
            $actual = & "${{ env.BUILD_DIRECTORY }}\GetApplicationInfo.ps1" -Url "${{ secrets.APP_MANIFEST_STAGING_URL }}"
            $next = "$($actual.Version.Major).$($actual.Version.Minor).$($actual.Version.Patch).$($actual.Version.Revision + 1)"
            Write-Host "Identificada nova versão $next a partir do manifesto atual do aplicativo..."

            echo "NEXT_VERSION=$next" >> $env:GITHUB_ENV     

    - name: "Publish"
      run: |
        msbuild ${{ env.CSPROJ_PATH }} /t:publish /p:Configuration="${{ env.BUILD_CONFIGURATION }}" /p:Platform="${{ env.BUILD_PLATFORM }}" /p:ApplicationVersion="${{ env.NEXT_VERSION }}" /p:MinimumRequiredVersion="${{ env.NEXT_VERSION }}" /p:VersionAssembly="${{ env.NEXT_VERSION }}"
    
    - name: "Setup WinSCP"
      run: |
        choco install winscp -y
    
    - name: "Deploy Files"
      run: |        
        winscp.com /command "open ftp://${{ secrets.FTP_USER }}`:${{ secrets.FTP_PASSWD }}@${{ secrets.FTP_HOSTNAME }}`:${{ secrets.FTP_PORT }}" "option batch on" "option confirm off" "put ${{ env.OUTPUT_DIRECTORY }}\* /docoffee/" "exit"

    - name: "Notify Team on Google Chat"
      run: |
        $webhookUrl = "https://chat.googleapis.com/v1/spaces/${{ secrets.GOOGLE_CHAT_SPACE }}/messages?key=${{ secrets.GOOGLE_CHAT_KEY }}&token=${{ secrets.GOOGLE_CHAT_TOKEN }}"        
        $environmentName = @{$true="Produção";$false="Homologação"}["${{ env.BUILD_CONFIGURATION }}" -eq "Release"]
        $body = @{ "text" = "Publicada versão *${{ env.NEXT_VERSION }}* do aplicativo *DoCoffee* no ambiente de $environmentName." } | ConvertTo-Json
        Invoke-RestMethod -Method POST -Uri $webhookUrl -Body $body -ContentType "application/json"
