name: 'Deploy DoCoffee'

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/DoCoffee.App/**'

  workflow_dispatch: # Allow you to run this workflow manually from the Action tab
  
env:
  BUILD_CONFIGURATION: Release
  BUILD_PLATFORM: AnyCPU
  CSPROJ_PATH: src\DoCoffee.App\DoCoffee.App.csproj
  HELLO_ARTIFACT_NAME: DoCoffee.App
  OUTPUT_DIRECTORY: ${{ github.workspace }}\src\DoCoffee.App\bin\Release\app.publish
      
jobs:

  build-and-publish:
    runs-on: windows-latest 
    
    steps:

    - name: "Checkout Code"
      uses: actions/checkout@v4

    - name: "Change App.config"
      uses: microsoft/variable-substitution@v1 
      with:
          files: './src/DoCoffee.App/App.config'
      env:
        ApiKey: ${{ secrets.API_KEY }}
                    
    - name: 'Setup MSBuild'
      uses: microsoft/setup-msbuild@v2

    - name: 'Setup Nuget'
      uses: nuget/setup-nuget@v2

    - name: 'Nuget Restore Packages'
      run: nuget restore ${{ env.CSPROJ_PATH }} -PackagesDirectory "src/packages"
      
    - name: "Increment Revision"
      id: 'incrementRevision'
      run: |
            $body = @{url="${{ secrets.APP_MANIFEST_URL }}"}
            $contentType = "application/x-www-form-urlencoded"
            $url = "${{ secrets.FUNCTION_CLICKONCE_DISCOVERY_URL }}"
            $payload = Invoke-RestMethod -Method POST -Uri $url -body $body -ContentType $contentType

            $nextVersion = "$($payload.version.major).$($payload.version.minor).$($payload.version.patch).$($payload.version.revision + 1)"

            Write-Host "Identificada nova versão $nextVersion do aplicativo..."

            echo "NEXT_VERSION=$nextVersion" >> $env:GITHUB_ENV     

    - name: "Publish"
      run: |
        msbuild ${{ env.CSPROJ_PATH }} /t:publish /p:Configuration="${{ env.BUILD_CONFIGURATION }}" /p:Platform="${{ env.BUILD_PLATFORM }}" /p:ApplicationVersion="${{ env.NEXT_VERSION }}" /p:MinimumRequiredVersion="${{ env.NEXT_VERSION }}" /p:VersionAssembly="${{ env.NEXT_VERSION }}"
    
    - name: "Setup WinSCP"
      run: |
        choco install winscp -y
    
    - name: "Deploy Files"
      run: |        
        winscp.com /command "open ftp://${{ secrets.FTP_USER }}`:${{ secrets.FTP_PASSWD }}@${{ secrets.FTP_HOSTNAME }}`:${{ secrets.FTP_PORT }}" "option batch on" "option confirm off" "put ${{ env.OUTPUT_DIRECTORY }}\* /docoffee/" "exit"







