name: 'Deploy DoCoffee (Staging)'

on:
  push:
    branches: [ "staging" ]
    paths:
      - 'src/DoCoffee.App/**'

  workflow_dispatch: # Allow you to run this workflow manually from the Action tab
  
env:
  BUILD_CONFIGURATION: Staging
  BUILD_PLATFORM: AnyCPU
  CSPROJ_PATH: src\DoCoffee.App\DoCoffee.App.csproj
  APPLICATION_DIRECTORY: ${{ github.workspace }}\src\DoCoffee.App  
  OUTPUT_DIRECTORY: ${{ github.workspace }}\src\DoCoffee.App\bin\Staging\app.publish
  BUILD_DIRECTORY: ${{ github.workspace }}\build
      
jobs:

  build-and-publish:
    runs-on: windows-latest 
    
    steps:

    - name: "Checkout Code"
      uses: actions/checkout@v4

    - name: "Prepare App.config"
      run: |            
            $appConfigPath = "${{ env.APPLICATION_DIRECTORY }}\App.Staging.config"

            Set-Location ${{ env.BUILD_DIRECTORY }}

            Write-Host "Generating EncryptionKey..."
            $encryptionKey = .\GenerateEncryptionKey.ps1
            
            Write-Host "Encrypting secret with EncryptionKey..."
            $mySecret = .\Encrypt.ps1 -Value "${{ secrets.MY_SECRET }}" -EncryptionKey $encryptionKey

            Write-Host "Updating AppSettings with encrypted secret..."
            .\UpdateAppSettings.ps1 -FilePath $appConfigPath -Key "MySecret" -Value $mySecret

            Write-Host "Updating resx with EncryptionKey..."
            .\UpdateResx.ps1 -FilePath "${{ env.APPLICATION_DIRECTORY }}\Properties\Resources.resx" -Key "EncryptionKey" -Value $encryptionKey
                    
    - name: 'Setup MSBuild'
      uses: microsoft/setup-msbuild@v2

    - name: 'Setup Nuget'
      uses: nuget/setup-nuget@v2

    - name: 'Nuget Restore Packages'
      run: nuget restore ${{ env.CSPROJ_PATH }} -PackagesDirectory "src/packages"
      
    - name: "Increment Revision"     
      run: |

            Set-Location ${{ env.BUILD_DIRECTORY }}
            $actualVersion = .\GetApplicationInfo.ps1 -Url "${{ secrets.APP_MANIFEST_STAGING_URL }}"
            $nextVersion = "$($actualVersion.Version.Major).$($actualVersion.Version.Minor).$($actualVersion.Version.Patch).$($actualVersion.Version.Revision + 1)"
            Write-Host "Identificada nova versão $nextVersion a partir do manifesto atual do aplicativo..."

            echo "NEXT_VERSION=$nextVersion" >> $env:GITHUB_ENV     

    - name: "Publish"
      run: |
        msbuild ${{ env.CSPROJ_PATH }} /t:publish /p:Configuration="${{ env.BUILD_CONFIGURATION }}" /p:Platform="${{ env.BUILD_PLATFORM }}" /p:ApplicationVersion="${{ env.NEXT_VERSION }}" /p:MinimumRequiredVersion="${{ env.NEXT_VERSION }}" /p:VersionAssembly="${{ env.NEXT_VERSION }}"
    
    - name: "Setup WinSCP"
      run: |
        choco install winscp -y
    
    - name: "Deploy Files"
      run: |        
        winscp.com /command "open ftp://${{ secrets.FTP_USER }}`:${{ secrets.FTP_PASSWD }}@${{ secrets.FTP_HOSTNAME }}`:${{ secrets.FTP_PORT }}" "option batch on" "option confirm off" "put ${{ env.OUTPUT_DIRECTORY }}\* /docoffee/" "exit"

    - name: "Notify Team in Google Chat"
      run: |
        $webhookUrl = "https://chat.googleapis.com/v1/spaces/${{ secrets.GOOGLE_CHAT_SPACE }}/messages?key=${{ secrets.GOOGLE_CHAT_KEY }}&token=${{ secrets.GOOGLE_CHAT_TOKEN }}"        
        $environmentName = @{$true="Produção";$false="Homologação"}["${{ env.BUILD_CONFIGURATION }}" -eq "Release"]
        $body = @{ "text" = "Publicada versão *${{ env.NEXT_VERSION }}* do aplicativo *DoCoffee* no ambiente de $environmentName." } | ConvertTo-Json
        Invoke-RestMethod -Method POST -Uri $webhookUrl -Body $body -ContentType "application/json"